name: MainServer

on:
  push:
    branches:
      - main
      - githubAction

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20'

      # - name: Build React App
      #   run: |
      #     cd web/front
      #     npm install
      #     npm run build
      #   env:
      #     CI: false

      # - name: Copy build to Spring Boot static folder
      #   run: |
      #     mkdir -p web/back/src/main/resources/static/
      #     cp -r web/front/build/* web/back/src/main/resources/static/

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Decode .p12 File
        run: |
          cd web/back/src/main/resources
          touch keystore.p12
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > keystore.p12

      - name: Build Spring Boot App
        run: |
          cd web/back
          touch src/main/resources/env.properties
          cat <<EOT >> src/main/resources/env.properties
          SPRING_JWT_SECRET= ${{ secrets.SPRING_JWT_SECRET }}
          NAVER_CLIENT_ID= ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET= ${{ secrets.NAVER_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID= ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET= ${{ secrets.GOOGLE_CLIENT_SECRET }}

          edgeservers.ip= ${{ secrets.EDGESERVER_IP }}
          edgeservers.id= ${{ secrets.EDGESERVER_ID }}
          edgeservers.user.id= ${{ secrets.EDGESERVER_USER_ID }}
          edgeservers.password= ${{ secrets.EDGESERVER_PASSWORD }}
          edgeservers.memoryTotal= ${{ secrets.EDGESERVER_MEMORYTOTAL }}
          edgeservers.memoryUse= ${{ secrets.EDGESERVER_MEMORYUSE }}
          edgeserver.number= ${{ secrets.EDGESERVER_NUMBER }}

          KEY_STORE_PASSWORD = ${{ secrets.KEY_STORE_PASSWORD }}
          EOT
          chmod +x ./gradlew
          ./gradlew build
          

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "web/back/build/libs/*.jar"
          target: "NEO_mainServer"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo systemctl restart neo.service